--USE MASTER;

/*CREATE DATABASE CrudNetCore6DataBaseFirst;
GO
*/
USE CrudNetCore6DataBaseFirst;
GO

DROP TABLE dbo.LIBRO;

CREATE TABLE dbo.LIBRO
(
	Id INT NOT NULL IDENTITY(1,1),
	Titulo NVARCHAR(50) NOT NULL,
	Descripcion NVARCHAR(300) NOT NULL,
	FechaLanzamiento DATETIME NOT NULL,
	Autor NVARCHAR(100) NOT NULL,
	Precio NUMERIC(5,2) NOT NULL,
	

	CONSTRAINT PK_LIBRO PRIMARY KEY(Id),
);
GO