--USE MASTER;

/*CREATE DATABASE CrudNetCore6DataBaseFirst;
GO
*/
USE CrudNetCore6DataBaseFirst;
GO

DROP TABLE dbo.LIBRO;

CREATE TABLE dbo.LIBRO
(
	Id INT NOT NULL IDENTITY(1,1),
	Titulo NVARCHAR(50) NOT NULL,
	Descripcion NVARCHAR(300) NOT NULL,
	FechaLanzamiento DATETIME NOT NULL,
	Autor NVARCHAR(100) NOT NULL,
	Precio NUMERIC(5,2) NOT NULL,
	

	CONSTRAINT PK_LIBRO PRIMARY KEY(Id),
);
GO
INSERT INTO LIBRO VALUES('Libro 1', 'Descripcion 1', '2022-01-01', 'Autor 1', 12);
INSERT INTO LIBRO VALUES('Libro 2', 'Descripcion 2', '2022-02-03', 'Autor 2', 34);